// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udsproxacchluxotubqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkc3Byb3hhY2NobHV4b3R1YnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODk1ODUsImV4cCI6MjA2MDQ2NTU4NX0.DXShgo6Cat7azHeli_HEcL1Sno6FJYe_CEpMbjxd3CQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);